"""add at risk state table.

Revision ID: d4b7f2a91c3e
Revises: f11ae5c358b0
Create Date: 2026-07-20 12:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4b7f2a91c3e"
down_revision: Union[str, Sequence[str], None] = "f11ae5c358b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atriskstaterecord",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("at_risk", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("missed_deadlines", sa.Boolean(), nullable=False),
        sa.Column("inactive", sa.Boolean(), nullable=False),
        sa.Column("low_progress", sa.Boolean(), nullable=False),
        sa.Column("low_feedback", sa.Boolean(), nullable=False),
        sa.Column("thresholds_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_atriskstaterecord_learner_id"), "atriskstaterecord", ["learner_id"], unique=False
    )
    op.create_index(
        op.f("ix_atriskstaterecord_run_date"), "atriskstaterecord", ["run_date"], unique=False
    )
    op.create_index(
        "uq_atriskstaterecord_learner_rundate",
        "atriskstaterecord",
        ["learner_id", "run_date"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_atriskstaterecord_learner_rundate", table_name="atriskstaterecord")
    op.drop_index(op.f("ix_atriskstaterecord_run_date"), table_name="atriskstaterecord")
    op.drop_index(op.f("ix_atriskstaterecord_learner_id"), table_name="atriskstaterecord")
    op.drop_table("atriskstaterecord")
    # ### end Alembic commands ###
