"""add notification record table.

Revision ID: f11ae5c358b0
Revises: b25d38b0cd7c
Create Date: 2026-07-15 16:26:59.806970

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11ae5c358b0'
down_revision: Union[str, Sequence[str], None] = 'b25d38b0cd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationrecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('SESSION_REMINDER', 'DEADLINE_REMINDER', 'AT_RISK_NUDGE', 'FEEDBACK_FOLLOWUP', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='notificationstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificationrecord_dedup_key'), 'notificationrecord', ['dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificationrecord_dedup_key'), table_name='notificationrecord')
    op.drop_table('notificationrecord')
    # ### end Alembic commands ###
