"""Prometheus metrics configuration for the application.

This module sets up and configures Prometheus metrics for monitoring the application.
"""

from prometheus_client import Counter, Histogram, Gauge

try:
    from starlette_prometheus import metrics, PrometheusMiddleware
except ModuleNotFoundError:
    metrics = None
    PrometheusMiddleware = None

# Request metrics
http_requests_total = Counter("http_requests_total", "Total number of HTTP requests", ["method", "endpoint", "status"])

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds", "HTTP request duration in seconds", ["method", "endpoint"]
)

# Database metrics
db_connections = Gauge("db_connections", "Number of active database connections")

# Custom business metrics
orders_processed = Counter("orders_processed_total", "Total number of orders processed")

llm_inference_duration_seconds = Histogram(
    "llm_inference_duration_seconds",
    "Time spent processing LLM inference",
    ["model"],
    buckets=[0.1, 0.3, 0.5, 1.0, 2.0, 5.0],
)


llm_stream_duration_seconds = Histogram(
    "llm_stream_duration_seconds",
    "Time spent processing LLM stream inference",
    ["model"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

session_names_generated_total = Counter(
    "session_names_generated_total",
    "Total session names generated by the LLM",
    ["status"],  # "success" | "error"
)

escalation_routing_total = Counter(
    "escalation_routing_total",
    "Total routing decisions made by the Week 2 escalation router",
    ["route", "trigger"],
)

session_ticket_links_total = Counter(
    "session_ticket_links_total",
    "Total session-to-ticket links written by the escalation flow",
    ["status"],
)


def setup_metrics(app):
    """Set up Prometheus metrics middleware and endpoints.

    Args:
        app: FastAPI application instance
    """
    if PrometheusMiddleware is None or metrics is None:
        return

    # Add Prometheus middleware
    app.add_middleware(PrometheusMiddleware)

    # Add metrics endpoint
    app.add_route("/metrics", metrics)
